version: '2'
services:
  service:
    image: docker.test:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    environment:
      - spring.profiles.active=dev
    container_name: dockerTest