POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "account": "zjb",
  "password": "123456",
  "signature": "1"
}

###
GET http://localhost:8080/api/v1/user/logout
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkMzM2ZTk3NS0zYjYyLTRhYTUtOTBmYS1kNGJkNTE3N2VkNmYiLCJubyI6MTI2ODE3ODYwNDYzODk5ODUzMCwic2lnbmF0dXJlIjoiMSIsIm5iZiI6MTU5MTM1NTI2OSwiZXhwIjoxNTkxNDQxNjY5fQ.DVYkVhWKHSsvDbAducCRYDLXejab_6y6uUxowsgzEMMsjxnZ9RSy3LXNrYyCt-LZqNEQhYiCbIHyDvOzE_L-Pw
###

GET http://localhost:8080/api/v1/user/logout
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YjNjNzRiNi0xNzliLTQ0ZGQtYWRlMC1iYjQzNmViOTYzNjAiLCJubyI6MTI2ODE3ODYwNDYzODk5ODUzMCwic2lnbmF0dXJlIjoiMSIsIm5iZiI6MTU5MTM1MDAzOCwiZXhwIjoxNTkxNDM2NDM4fQ.oegN4wsogpEReNPzipeCKMBOKOQ1R8m0schhpH-SlqLL5ekeCxMuQzbHel7_ZrdFnR44USbirNbBlqhXNac5Hw
###