POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "account": "zjb",
  "password": "123456"
}

###
GET http://localhost:8080/api/v1/user/logout
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1Y2M0ZWVhYS02OTJkLTQ5ZDYtOGRiYS0xMTdhNjgzODlmNDQiLCJubyI6MTI2ODE3ODYwNDYzODk5ODUzMCwibmJmIjoxNTkxMjg1MzM0LCJleHAiOjE1OTEzNzE3MzR9.IE0FbtWuxfXhkxpkDd9UxTos0jUs8cop0oVVBmdp9KGfPatbXF0cjJBmYQG65_9Upaf2pm7TbUO_Sc41zn0tFg
###

GET http://localhost:8080/api/v1/user/logout
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1Y2M0ZWVhYS02OTJkLTQ5ZDYtOGRiYS0xMTdhNjgzODlmNDQiLCJubyI6MTI2ODE3ODYwNDYzODk5ODUzMCwibmJmIjoxNTkxMjg1MzM0LCJleHAiOjE1OTEzNzE3MzR9.IE0FbtWuxfXhkxpkDd9UxTos0jUs8cop0oVVBmdp9KGfPatbXF0cjJBmYQG65_9Upaf2pm7TbUO_Sc41zn0tFg
###