POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
  "account": "zjb",
  "password": "123456",
  "signature": "2"
}

###
GET http://localhost:8080/api/v1/user/logout
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZjQ4NTE2My1jZjNiLTQ1M2YtOTljNC1jN2Q3NjRiMmMyN2EiLCJubyI6MTI2ODE3ODYwNDYzODk5ODUzMCwic2lnbmF0dXJlIjoiMiIsIm5iZiI6MTU5MTQyNTQwMywiZXhwIjoxNTkxNTExODAzfQ.sHs03Kea8DjoGI47LbFMUki5Zk7fq7QjioQPi0aRaUiwtWymOll-68LcQ6jsLH4bjEAA0Gem50XE1J03jQt11g
###

GET http://localhost:8080/api/v1/user/logout
token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2YjNjNzRiNi0xNzliLTQ0ZGQtYWRlMC1iYjQzNmViOTYzNjAiLCJubyI6MTI2ODE3ODYwNDYzODk5ODUzMCwic2lnbmF0dXJlIjoiMSIsIm5iZiI6MTU5MTM1MDAzOCwiZXhwIjoxNTkxNDM2NDM4fQ.oegN4wsogpEReNPzipeCKMBOKOQ1R8m0schhpH-SlqLL5ekeCxMuQzbHel7_ZrdFnR44USbirNbBlqhXNac5Hw
###