
# 配置数据库
spring:
  redis:
    database: 0
    host: 39.97.106.60
    port: 6379
    timeout: 6000  # 连接超时时长（毫秒）
  snowflake:
    workerId: 1
    dataCenterId: 1
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://39.97.106.60/senior-mall?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
          username: root
          password: 111111
          driver-class-name: com.mysql.cj.jdbc.Driver
        ylfw:
          url: jdbc:mysql://39.97.106.60/ylfw?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
          username: root
          password: 111111
          driver-class-name: com.mysql.cj.jdbc.Driver

#  设置是否开启跨域
access-control-allow-origin-enable: true

jwt:
  key: old-man-mall-service
token:
  expire:
    seconds: 86400

#logging:
#    level:
#      root: debug
server:
  port: 8081
