package cn.infomany.handler.mybatisplus;

import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.function.Supplier;

@Component
public class AutoGenerateDate implements Supplier<Object> {

    @Override
    public Object get() {
        return new Date();
    }
}
