package cn.infomany.handler.mybatisplus;

import org.springframework.stereotype.Component;

import java.util.Date;
import java.util.function.Supplier;

/**
 * 自动生成时间Date
 * 配合{@link cn.infomany.common.anno.TableAuto}使用
 *
 * @author zjb
 */
@Component
public class AutoGenerateDate implements Supplier<Object> {

    @Override
    public Object get() {
        return new Date();
    }
}
